export const STORAGE_URL = 'https://storage.bunnycdn.com/materialdesignnative';
export const ACCESS_KEY = 'ba8dd74c-5844-4d83-8523b4a5f50d-a128-4190';
export const HOME_MENU = [
    {
        title: 'Music',
        category: 'music',
        icon: require('../assets/icon/logo_activity.png'),
        data: [
            { title: 'Music Style 1', action: 'music1' },
            { title: 'Music Style 2', action: 'music2' },
            { title: 'Music Style 3', action: 'music3' },
            { title: 'Music Style 4', action: 'music4' },
            { title: 'Music Style 5', action: 'music5' },
            { title: 'Music Style 6', action: 'music6' },
            { title: 'Music Style 7', action: 'music7' },
            { title: 'Music Style 8', action: 'music8' },
            { title: 'Music Style 9', action: 'music9' },
            { title: 'Music Style 10', action: 'music10' },
            { title: 'Music Style 11', action: 'music11' },
            { title: 'Music Style 12', action: 'music12' },
            { title: 'Music Style 13', action: 'music13' },
            { title: 'Music Style 14', action: 'music14' },
        ]
    },
    {
        title: 'Activity',
        category: 'activity',
        icon: require('../assets/icon/logo_activity.png'),
        data: [
            { title: 'Activity Style 1', action: 'activity1' },
            { title: 'Activity Style 2', action: 'activity2' },
            { title: 'Activity Style 3', action: 'activity3' },
            { title: 'Activity Style 4', action: 'activity4' },
            { title: 'Activity Style 5', action: 'activity5' },
            { title: 'Activity Style 6', action: 'activity6' },
            { title: 'Activity Style 7', action: 'activity7' },
            { title: 'Activity Style 8', action: 'activity8' },
            { title: 'Activity Style 9', action: 'activity9' },
            { title: 'Activity Style 10', action: 'activity10' },
            { title: 'Activity Style 11', action: 'activity11' },
            { title: 'Activity Style 12', action: 'activity12' },
            { title: 'Activity Style 13', action: 'activity13' },
            { title: 'Activity Style 14', action: 'activity14' },
            { title: 'Activity Style 15', action: 'activity15' },
            { title: 'Activity Style 16', action: 'activity16' },
            { title: 'Activity Style 17', action: 'activity17' },
            { title: 'Activity Style 18', action: 'activity18' },
            { title: 'Activity Style 19', action: 'activity19' },
            { title: 'Activity Style 20', action: 'activity20' },
            { title: 'Activity Style 21', action: 'activity21' },
            { title: 'Activity Style 22', action: 'activity22' },
            { title: 'Activity Style 23', action: 'activity23' },
            { title: 'Activity Style 24', action: 'activity24' },
            { title: 'Activity Style 25', action: 'activity25' },
            { title: 'Activity Style 26', action: 'activity26' },
            { title: 'Activity Style 27', action: 'activity27' },
            { title: 'Activity Style 28', action: 'activity28' },
            { title: 'Activity Style 29', action: 'activity29' },
            { title: 'Activity Style 30', action: 'activity30' },
        ]
    },
    {
        title: 'Dashboard',
        category: 'dashboard',
        icon: require('../assets/icon/logo_dashboard.png'),
        data: [
            { title: 'Dashboard Style 1', action: 'dashboard1' },
            { title: 'Dashboard Style 2', action: 'dashboard2' },
            { title: 'Dashboard Style 3', action: 'dashboard3' },
            { title: 'Dashboard Style 4', action: 'dashboard4' },
            { title: 'Dashboard Style 5', action: 'dashboard5' },
        ]
    },
    {
        title: 'Login & Sign Up',
        category: 'login',
        icon: require('../assets/icon/logo_login.png'),
        data: [
            { title: 'Sign Up Style 1', action: 'login1' },
            { title: 'Sign Up Style 2', action: 'login2' },
            { title: 'Sign Up Style 3', action: 'login3' },
            { title: 'Sign Up Style 4', action: 'login4' },
            { title: 'Sign Up Style 5', action: 'login5' },
            { title: 'Sign Up Style 6', action: 'login6' },
            { title: 'Sign Up Style 7', action: 'login7' },
            { title: 'Sign Up Style 8', action: 'login8' },
            { title: 'Sign Up Style 9', action: 'login9' },
            { title: 'Sign Up Style 10', action: 'login10' },
            { title: 'Sign In Style 1', action: 'login11' },
            { title: 'Sign In Style 2', action: 'login12' },
            { title: 'Sign In Style 3', action: 'login13' },
            { title: 'Sign In Style 4', action: 'login14' },
            { title: 'Sign In Style 5', action: 'login15' },
            { title: 'Sign In Style 6', action: 'login16' },
            { title: 'Sign In Style 7', action: 'login17' },
            { title: 'Sign In Style 8', action: 'login18' },
            { title: 'Sign In Style 9', action: 'login19' },
            { title: 'Sign In Style 10', action: 'login20' },
            { title: 'Welcome Style 1', action: 'login21' },
            { title: 'Welcome Style 2', action: 'login22' },
            { title: 'Welcome Style 3', action: 'login23' },
            { title: 'Forgot Password', action: 'login24' },
            { title: 'Verify Account', action: 'login25' },
        ]
    },
    {
        title: 'Walkthrough',
        category: 'walkthrough',
        icon: require('../assets/icon/logo_walkthrough.png'),
        data: [
            { title: 'Walkthrough Style 1', action: 'walkthrough1' },
            { title: 'Walkthrough Style 2', action: 'walkthrough2' },
            { title: 'Walkthrough Style 3', action: 'walkthrough3' },
            { title: 'Walkthrough Style 4', action: 'walkthrough4' },
            { title: 'Walkthrough Style 5', action: 'walkthrough5' },
            { title: 'Walkthrough Style 6', action: 'walkthrough6' },
            { title: 'Walkthrough Style 7', action: 'walkthrough7' },
            { title: 'Walkthrough Style 8', action: 'walkthrough8' },
            { title: 'Walkthrough Style 9', action: 'walkthrough9' },
            { title: 'Walkthrough Style 10', action: 'walkthrough10' },
            { title: 'Walkthrough Style 11', action: 'walkthrough11' },
            { title: 'Walkthrough Style 12', action: 'walkthrough12' },
            { title: 'Walkthrough Style 13', action: 'walkthrough13' },
            { title: 'Walkthrough Style 14', action: 'walkthrough14' },
            { title: 'Walkthrough Style 15', action: 'walkthrough15' },
            { title: 'Walkthrough Style 16', action: 'walkthrough16' },
            { title: 'Walkthrough Style 17', action: 'walkthrough17' },
            { title: 'Walkthrough Style 18', action: 'walkthrough18' },
            { title: 'Walkthrough Style 19', action: 'walkthrough19' },
            { title: 'Walkthrough Style 20', action: 'walkthrough20' },
        ]
    },
    {
        title: 'Menu',
        category: 'menu',
        icon: require('../assets/icon/logo_menu.png'),
        data: [
            { title: 'Menu Style 1', action: 'menu1' },
            { title: 'Menu Style 2', action: 'menu2' },
            { title: 'Menu Style 3', action: 'menu3' },
            { title: 'Menu Style 4', action: 'menu4' },
            { title: 'Menu Style 5', action: 'menu5' },
            { title: 'Menu Style 6', action: 'menu6' },
            { title: 'Menu Style 7', action: 'menu7' },
            { title: 'Menu Style 8', action: 'menu8' },
            { title: 'Menu Style 9', action: 'menu9' },
            { title: 'Menu Style 10', action: 'menu10' },
            { title: 'Menu Style 11', action: 'menu11' },
            { title: 'Menu Style 12', action: 'menu12' },
            { title: 'Menu Style 13', action: 'menu13' },
            { title: 'Menu Style 14', action: 'menu14' },
            { title: 'Menu Style 15', action: 'menu15' },
            { title: 'Menu Style 16', action: 'menu16' },
            { title: 'Menu Style 17', action: 'menu17' },
            { title: 'Menu Style 18', action: 'menu18' },
            { title: 'Menu Style 19', action: 'menu19' },
            { title: 'Menu Style 20', action: 'menu20' },
        ]
    },
    {
        title: 'Profile',
        category: 'profile',
        icon: require('../assets/icon/logo_profile.png'),
        data: [
            { title: 'Profile Style 1', action: 'profile1' },
            { title: 'Profile Style 2', action: 'profile2' },
            { title: 'Profile Style 3', action: 'profile3' },
            { title: 'Profile Style 4', action: 'profile4' },
            { title: 'Profile Style 5', action: 'profile5' },
            { title: 'Profile Style 6', action: 'profile6' },
            { title: 'Profile Style 7', action: 'profile7' },
            { title: 'Profile Style 8', action: 'profile8' },
            { title: 'Profile Style 9', action: 'profile9' },
            { title: 'Profile Style 10', action: 'profile10' },
            { title: 'Profile Style 11', action: 'profile11' },
            { title: 'Profile Style 12', action: 'profile12' },
            { title: 'Profile Style 13', action: 'profile13' },
            { title: 'Profile Style 14', action: 'profile14' },
            { title: 'Profile Style 15', action: 'profile15' },
            { title: 'Profile Style 16', action: 'profile16' },
            { title: 'Profile Style 17', action: 'profile17' },
            { title: 'Profile Style 18', action: 'profile18' },
            { title: 'Profile Style 19', action: 'profile19' },
            { title: 'Profile Style 20', action: 'profile20' },
            { title: 'Profile Style 21', action: 'profile21' },
            { title: 'Profile Style 22', action: 'profile22' },
            { title: 'Profile Style 23', action: 'profile23' },
            { title: 'Profile Style 24', action: 'profile24' },
            { title: 'Profile Style 25', action: 'profile25' },
            { title: 'Profile Style 26', action: 'profile26' },
            { title: 'Profile Style 27', action: 'profile27' },
            { title: 'Profile Style 28', action: 'profile28' },
            { title: 'Profile Style 29', action: 'profile29' },
            { title: 'Profile Style 30', action: 'profile30' },
        ]
    },
    {
        title: 'Ecommerce',
        category: 'ecommerce',
        icon: require('../assets/icon/logo_ecommerce.png'),
        data: [
            { title: 'Ecommerce Style 1', action: 'ecommerce1' },
            { title: 'Ecommerce Style 2', action: 'ecommerce2' },
            { title: 'Ecommerce Style 3', action: 'ecommerce3' },
            { title: 'Ecommerce Style 4', action: 'ecommerce4' },
            { title: 'Ecommerce Style 5', action: 'ecommerce5' },
            { title: 'Ecommerce Style 6', action: 'ecommerce6' },
            { title: 'Ecommerce Style 7', action: 'ecommerce7' },
            { title: 'Ecommerce Style 8', action: 'ecommerce8' },
            { title: 'Ecommerce Style 9', action: 'ecommerce9' },
            { title: 'Ecommerce Style 10', action: 'ecommerce10' },
            { title: 'Ecommerce Style 11', action: 'ecommerce11' },
            { title: 'Ecommerce Style 12', action: 'ecommerce12' },
            { title: 'Ecommerce Style 13', action: 'ecommerce13' },
            { title: 'Ecommerce Style 14', action: 'ecommerce14' },
            { title: 'Ecommerce Style 15', action: 'ecommerce15' },
            { title: 'Ecommerce Style 16', action: 'ecommerce16' },
            { title: 'Ecommerce Style 17', action: 'ecommerce17' },
            { title: 'Ecommerce Style 18', action: 'ecommerce18' },
            { title: 'Ecommerce Style 19', action: 'ecommerce19' },
            { title: 'Ecommerce Style 20', action: 'ecommerce20' },
            { title: 'Ecommerce Style 21', action: 'ecommerce21' },
            { title: 'Ecommerce Style 22', action: 'ecommerce22' },
            { title: 'Ecommerce Style 23', action: 'ecommerce23' },
            { title: 'Ecommerce Style 24', action: 'ecommerce24' },
            { title: 'Ecommerce Style 25', action: 'ecommerce25' },
            { title: 'Ecommerce Style 26', action: 'ecommerce26' },
            { title: 'Ecommerce Style 27', action: 'ecommerce27' },
            { title: 'Ecommerce Style 28', action: 'ecommerce28' },
            { title: 'Ecommerce Style 29', action: 'ecommerce29' },
            { title: 'Ecommerce Style 30', action: 'ecommerce30' },
        ]
    },
    {
        title: 'Gallery',
        category: 'gallery',
        icon: require('../assets/icon/logo_gallery.png'),
        data: [
            { title: 'Gallery Style 1', action: 'gallery1' },
            { title: 'Gallery Style 2', action: 'gallery2' },
            { title: 'Gallery Style 3', action: 'gallery3' },
            { title: 'Gallery Style 4', action: 'gallery4' },
            { title: 'Gallery Style 5', action: 'gallery5' },
            { title: 'Gallery Style 6', action: 'gallery6' },
            { title: 'Gallery Style 7', action: 'gallery7' },
            { title: 'Gallery Style 8', action: 'gallery8' },
            { title: 'Gallery Style 9', action: 'gallery9' },
            { title: 'Gallery Style 10', action: 'gallery10' },
            { title: 'Gallery Style 11', action: 'gallery11' },
            { title: 'Gallery Style 12', action: 'gallery12' },
            { title: 'Gallery Style 13', action: 'gallery13' },
            { title: 'Gallery Style 14', action: 'gallery14' },
            { title: 'Gallery Style 15', action: 'gallery15' },
            { title: 'Gallery Style 16', action: 'gallery16' },
            { title: 'Gallery Style 17', action: 'gallery17' },
            { title: 'Gallery Style 18', action: 'gallery18' },
            { title: 'Gallery Style 19', action: 'gallery19' },
            { title: 'Gallery Style 20', action: 'gallery20' },
            { title: 'Gallery Style 21', action: 'gallery21' },
            { title: 'Gallery Style 22', action: 'gallery22' },
            { title: 'Gallery Style 23', action: 'gallery23' },
            { title: 'Gallery Style 24', action: 'gallery24' },
            { title: 'Gallery Style 25', action: 'gallery25' },
        ]
    },
    {
        title: 'Button, Card & Chips',
        category: 'chips',
        icon: require('../assets/icon/logo_chips.png'),
        data: [
            {title: 'Chips Style 1', action: 'chips1'},
            {title: 'Chips Style 2', action: 'chips2'},
            {title: 'Chips Style 3', action: 'chips3'},
            {title: 'Chips Style 4', action: 'chips4'},
            {title: 'Chips Style 5', action: 'chips5'},
            {title: 'Chips Style 6', action: 'chips6'},
            {title: 'Chips Style 7', action: 'chips7'},
            {title: 'Chips Style 8', action: 'chips8'},
            {title: 'Chips Style 9', action: 'chips9'},
            {title: 'Chips Style 10', action: 'chips10'},
            {title: 'Chips Style 11', action: 'chips11'},
            {title: 'Chips Style 12', action: 'chips12'},
            {title: 'Chips Style 13', action: 'chips13'},
            {title: 'Chips Style 14', action: 'chips14'},
            {title: 'Chips Style 15', action: 'chips15'},
        ]
    },
    {
        title: 'Navigation & Bottom Sheet',
        category: 'bottom',
        icon: require('../assets/icon/logo_bottom.png'),
        data: [
            {title: 'Bottom Style 1', action: 'bottom1'},
            {title: 'Bottom Style 2', action: 'bottom2'},
            {title: 'Bottom Style 3', action: 'bottom3'},
            {title: 'Bottom Style 4', action: 'bottom4'},
            {title: 'Bottom Style 5', action: 'bottom5'},
            {title: 'Bottom Style 6', action: 'bottom6'},
            {title: 'Bottom Style 7', action: 'bottom7'},
            {title: 'Bottom Style 8', action: 'bottom8'},
            {title: 'Bottom Style 9', action: 'bottom9'},
            {title: 'Bottom Style 10', action: 'bottom10'},
            {title: 'Bottom Style 11', action: 'bottom11'},
            {title: 'Bottom Style 12', action: 'bottom12'},
            {title: 'Bottom Style 13', action: 'bottom13'},
            {title: 'Bottom Style 14', action: 'bottom14'},
            {title: 'Bottom Style 15', action: 'bottom15'},
        ]
    },
    {
        title: 'Dialog View & Expansion Panel',
        category: 'dialog',
        icon: require('../assets/icon/logo_dialog.png'),
        data: [
            {title: 'Dialog Style 1', action: 'dialog1'},
            {title: 'Dialog Style 2', action: 'dialog2'},
            {title: 'Dialog Style 3', action: 'dialog3'},
            {title: 'Dialog Style 4', action: 'dialog4'},
            {title: 'Dialog Style 5', action: 'dialog5'},
            {title: 'Dialog Style 6', action: 'dialog6'},
            {title: 'Dialog Style 7', action: 'dialog7'},
            {title: 'Dialog Style 8', action: 'dialog8'},
            {title: 'Dialog Style 9', action: 'dialog9'},
            {title: 'Dialog Style 10', action: 'dialog10'},
            {title: 'Dialog Style 11', action: 'dialog11'},
            {title: 'Dialog Style 12', action: 'dialog12'},
            {title: 'Dialog Style 13', action: 'dialog13'},
            {title: 'Dialog Style 14', action: 'dialog14'},
            {title: 'Dialog Style 15', action: 'dialog15'},
            {title: 'Dialog Style 16', action: 'dialog16'},
            {title: 'Dialog Style 17', action: 'dialog17'},
            {title: 'Dialog Style 18', action: 'dialog18'},
            {title: 'Dialog Style 19', action: 'dialog19'},
            {title: 'Dialog Style 20', action: 'dialog20'},
        ]
    },
    {
        title: 'Search & Verification',
        category: 'verification',
        icon: require('../assets/icon/logo_verification.png'),
        data: [
            {title: 'Verification Style 1', action: 'verification1'},
            {title: 'Verification Style 2', action: 'verification2'},
            {title: 'Verification Style 3', action: 'verification3'},
            {title: 'Verification Style 4', action: 'verification4'},
            {title: 'Verification Style 5', action: 'verification5'},
            {title: 'Verification Style 6', action: 'verification6'},
            {title: 'Verification Style 7', action: 'verification7'},
            {title: 'Verification Style 8', action: 'verification8'},
            {title: 'Verification Style 9', action: 'verification9'},
            {title: 'Verification Style 10', action: 'verification10'},
            {title: 'Verification Style 11', action: 'verification11'},
            {title: 'Verification Style 12', action: 'verification12'},
            {title: 'Verification Style 13', action: 'verification13'},
            {title: 'Verification Style 14', action: 'verification14'},
            {title: 'Verification Style 15', action: 'verification15'},
            {title: 'Verification Style 16', action: 'verification16'},
            {title: 'Verification Style 17', action: 'verification17'},
            {title: 'Verification Style 18', action: 'verification18'},
            {title: 'Verification Style 19', action: 'verification19'},
            {title: 'Verification Style 20', action: 'verification20'},
        ]
    },
    {
        title: 'No Item Page / Empty State',
        category: 'noitem',
        icon: require('../assets/icon/logo_noitem.png'),
        data: [
            {title: 'No Item 1', action: 'noitem1'},
            {title: 'No Item 2', action: 'noitem2'},
            {title: 'No Item 3', action: 'noitem3'},
            {title: 'No Item 4', action: 'noitem4'},
            {title: 'No Item 5', action: 'noitem5'},
            {title: 'No Item 6', action: 'noitem6'},
            {title: 'No Item 7', action: 'noitem7'},
            {title: 'No Item 8', action: 'noitem8'},
            {title: 'No Item 9', action: 'noitem9'},
            {title: 'No Item 10', action: 'noitem10'},
            {title: 'No Item 11', action: 'noitem11'},
            {title: 'No Item 12', action: 'noitem12'},
            {title: 'No Item 13', action: 'noitem13'},
            {title: 'No Item 14', action: 'noitem14'},
            {title: 'No Item 15', action: 'noitem15'},
        ]
    },
    {
        title: 'Progress, Slider & Stepper',
        category: 'progress',
        icon: require('../assets/icon/logo_progress.png'),
        data: [
            { title: 'Progress Style 1', action: 'progress1' },
            { title: 'Progress Style 2', action: 'progress2' },
            { title: 'Progress Style 3', action: 'progress3' },
            { title: 'Progress Style 4', action: 'progress4' },
            { title: 'Progress Style 5', action: 'progress5' },
            { title: 'Progress Style 6', action: 'progress6' },
            { title: 'Progress Style 7', action: 'progress7' },
            { title: 'Progress Style 8', action: 'progress8' },
            { title: 'Progress Style 9', action: 'progress9' },
            { title: 'Progress Style 10', action: 'progress10' },
            { title: 'Progress Style 11', action: 'progress11' },
            { title: 'Progress Style 12', action: 'progress12' },
            { title: 'Progress Style 13', action: 'progress13' },
            { title: 'Progress Style 14', action: 'progress14' },
            { title: 'Progress Style 15', action: 'progress15' },
        ]
    },
    {
        title: 'News',
        category: 'news',
        icon: require('../assets/icon/logo_news.png'),
        data: [
            { title: 'News Style 1', action: 'news1' },
            { title: 'News Style 2', action: 'news2' },
            { title: 'News Style 3', action: 'news3' },
            { title: 'News Style 4', action: 'news4' },
            { title: 'News Style 5', action: 'news5' },
            { title: 'News Style 6', action: 'news6' },
            { title: 'News Style 7', action: 'news7' },
            { title: 'News Style 8', action: 'news8' },
            { title: 'News Style 9', action: 'news9' },
            { title: 'News Style 10', action: 'news10' },
            { title: 'News Style 11', action: 'news11' },
            { title: 'News Style 12', action: 'news12' },
            { title: 'News Style 13', action: 'news13' },
            { title: 'News Style 14', action: 'news14' },
            { title: 'News Style 15', action: 'news15' },
        ]
    },
    {
        title: 'Food',
        category: 'food',
        icon: require('../assets/icon/logo_food.png'),
        data: [
            { title: 'Food Style 1', action: 'food1' },
            { title: 'Food Style 2', action: 'food2' },
            { title: 'Food Style 3', action: 'food3' },
            { title: 'Food Style 4', action: 'food4' },
            { title: 'Food Style 5', action: 'food5' },
            { title: 'Food Style 6', action: 'food6' },
            { title: 'Food Style 7', action: 'food7' },
            { title: 'Food Style 8', action: 'food8' },
            { title: 'Food Style 9', action: 'food9' },
            { title: 'Food Style 10', action: 'food10' },
            { title: 'Food Style 11', action: 'food11' },
            { title: 'Food Style 12', action: 'food12' },
        ]
    },
    {
        title: 'Map',
        category: 'map',
        icon: require('../assets/icon/logo_map.png'),
        data: [
            { title: 'Map Style 1', action: 'map1' },
            { title: 'Map Style 2', action: 'map2' },
            { title: 'Map Style 3', action: 'map3' },
            { title: 'Map Style 4', action: 'map4' },
            { title: 'Map Style 5', action: 'map5' },
            { title: 'Map Style 6', action: 'map6' },
            { title: 'Map Style 7', action: 'map7' },
            { title: 'Map Style 8', action: 'map8' },
            { title: 'Map Style 9', action: 'map9' },
            { title: 'Map Style 10', action: 'map10' },
        ]
    },
];

